default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  port: 5433

development:
  <<: *default
  database: new_ckeditor_demo

test:
  <<: *default
  database: new_ckeditor_demo_test<%= ENV['TEST_ENV_NUMBER'] %> 

production:
  <<: *default
  database: new_ckeditor_demo
